name: weather_web
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  responsive_builder: ^0.7.1
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.4
  geolocator: ^12.0.0
  http: ^1.2.2
  carousel_slider: ^4.2.1
  flutter_switch: ^0.3.2
  liquid_swipe: ^3.1.0
  syncfusion_flutter_gauges: ^26.1.0
  onboarding_overlay: ^3.2.2
  shared_preferences: ^2.2.3
  animate_gradient: ^0.0.3
  draggable_home: ^1.0.5
  vitality: ^3.0.0
  weather_animation: ^1.1.0
  lottie: ^3.1.3
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0

flutter:

 
  uses-material-design: true

  
  assets:
    - assets/images/cold.gif
    - assets/images/hail.gif
    - assets/images/snow.gif
    - assets/images/cloud.gif
    - assets/images/rain.gif
    - assets/images/tornado.gif
    - assets/images/sun.gif
    - assets/images/freezing.gif
    - assets/images/storm.gif
    - assets/images/fog.gif
    - assets/images/smoke.gif
    - assets/images/drizzle.gif

  
